### ISSUE TITLE
Rubygems support needs to be updated

### ISSUE THREAD

**Issue by ch1ago** [kateinoigakukun/irb.wasm#16]
@kateinoigakukun

Hi. Thank you so much for releasing this project.

I learned about it from your talk at Ruby Kaigi 2022.

I tried to use it immediately and it worked perfectly well.

And I intend to use it on the website of a Ruby library I am developing.

I noticed this bug a few days ago, but I thought this could be a small hickup with Rubygems.

So I waited a little bit before reporting this.

Thank you for everything you do for the Ruby community.

```
irb(main):001:0> require "bundler/inline"
=> true
irb(main):002:0> gemfile do 
         source "https://rubygems.org" 
         gem "parser" 
       end
/usr/local/lib/ruby/3.2.0+3/bundler/fetcher/index.rb:21:in `rescue in specs': Could not fetch specs from https://rubygems.org/ due to underlying error <server did not return a valid file 
(https://irb-wasm-proxy.edgecompute.app/specs.4.8.gz)> (Bundler::HTTPError)
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher/index.rb:8:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:136:in `block in specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `drop_while'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:122:in `block in specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:40:in `run'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:30:in `attempt'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:121:in `specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:426:in `block in fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `each'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:405:in `block in remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/index.rb:9:in `build'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:401:in `remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:131:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/resolver.rb:212:in `index_for'
    ... 26 levels...
/usr/local/lib/ruby/3.2.0+3/rubygems/remote_fetcher.rb:254:in `rescue in fetch_path': server did not return a valid file (https://irb-wasm-proxy.edgecompute.app/specs.4.8.gz) (Gem::Remote
Fetcher::FetchError)
    from /usr/local/lib/ruby/3.2.0+3/rubygems/remote_fetcher.rb:251:in `fetch_path'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:451:in `fetch_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:459:in `fetch_all_remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher/index.rb:9:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:136:in `block in specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `drop_while'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:122:in `block in specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:40:in `run'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:30:in `attempt'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:121:in `specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:426:in `block in fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `each'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:405:in `block in remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/index.rb:9:in `build'
    ... 29 levels...
/usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `initialize': #<Zlib::GzipFile::Error: not in gzip format, input="\x1F......."> (Zlib::GzipFile::Error)
    from /usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `new'
    from /usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `gunzip'
    from /usr/local/lib/ruby/3.2.0+3/rubygems/remote_fetcher.rb:252:in `fetch_path'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:451:in `fetch_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:459:in `fetch_all_remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher/index.rb:9:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:136:in `block in specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `drop_while'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:122:in `block in specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:40:in `run'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:30:in `attempt'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:121:in `specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:426:in `block in fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `each'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `fetch_names'
    ... 31 levels...
/usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `initialize': not in gzip format (Zlib::GzipFile::Error)
    from /usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `new'
    from /usr/local/lib/ruby/3.2.0+3/rubygems/util.rb:18:in `gunzip'
    from /usr/local/lib/ruby/3.2.0+3/rubygems/remote_fetcher.rb:252:in `fetch_path'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:451:in `fetch_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/rubygems_integration.rb:459:in `fetch_all_remote_specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher/index.rb:9:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:136:in `block in specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `drop_while'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:135:in `specs'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:122:in `block in specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:40:in `run'
    from /usr/local/lib/ruby/3.2.0+3/bundler/retry.rb:30:in `attempt'
    from /usr/local/lib/ruby/3.2.0+3/bundler/fetcher.rb:121:in `specs_with_retry'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:426:in `block in fetch_names'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `each'
    from /usr/local/lib/ruby/3.2.0+3/bundler/source/rubygems.rb:419:in `fetch_names'
    ... 31 levels...
irb(main):006:0> 
irb(main):007:0> 
```

**Comment by kateinoigakukun** [comment]
Closed by #17
